---

# Note: You may want to install ppa manually first.

- name: install i3wm package
  apt:
    name: "{{item}}"
    state: "present"
    update_cache: yes
  loop:
    - i3
    - j4-dmenu-desktop
  when: ansible_facts['os_family'] == "Debian"

- name: copy i3m gpg key to remote machine
  copy:
    src: sur5r-keyring-2015.gpg
    dest: /etc/apt/
    backup: yes

- name: add i3wm gpg key
  apt_key:
    file: /etc/apt/sur5r-keyring-2015.gpg
    id: 'E3CA1A89941C42E6'
  when: ansible_facts['os_family'] == "Debian"

- name: install i3ipc pip package
  pip:
    name: i3ipc
  become: yes

- name: install lightDM menu entries
  copy:
    src: "{{item}}"
    dest: /usr/share/xsessions/{{item}}
  loop:
    - mate-xsession.desktop
    - i3-xsession.desktop

# - name: disable Xession ssh-agent startup script
# #   lineinfile:
# #     dest: /etc/X11/Xsession.options
# #     regexp: ^\s*use-ssh-agent
# #     line: "# use-ssh-agent"
# #     backrefs: yes
# #     state: present
#
#
