---
# file: tasks/main.yml

# specify the packages and the packager to use
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install required ppas on ubuntu machines
  apt_repository: repo="{{ item }}"
  with_items: "{{apt_ppas}}"
  when: ansible_distribution == "Ubuntu"

- name: install required repos on Debian derivatives
  apt_repository: repo="{{ item }}"
  with_items: "{{apt_repos}}"
  when: ansible_os_family == "Debian"

  # NetworkManager is sarting dnsmqaq with the '--no-hosts' options witch
  # prevents reading the OS '/etc/hosts' file.
  # To take effect, NetworkManager service needs to be restarted
- name: have networkmanager's dnsmqaq started reading '/etc/hosts'
  lineinfile:
    line: "addn-hosts=/etc/hosts"
    dest: "/etc/NetworkManager/dnsmasq.d/hosts.conf"
    owner: root
    group: root
    create: yes
    state: present
  when: ansible_distribution == "Ubuntu"

- name: install os packages
  package: name={{ workstation_pkgs }} state={{ workstation_pkg_state }}

- name: install pip packages
  command: "{{ '/usr/bin/pip3' if ansible_os_family == 'Debian' else '/usr/bin/pip' }} -q install {{workstation_pip_pkgs|join(' ')}}"
  become: yes
  register: pip_cmd_result
  changed_when: pip_cmd_result.rc == 0 and pip_cmd_result.stdout_lines == ""

- debug: var=pip_cmd_result.stdout_lines
  when: pip_cmd_result.stdout_lines

- name: install entr (fs watcher) on rhel by script
  script: install_entr.sh
  when: ansible_os_family != 'Debian'

- name: change dumpcap capabilities CAP_NET_RAW+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_RAW+eip'

- name: change dumpcap capabilities CAP_NET_ADMIN+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_ADMIN+eip'
