---
# file: tasks/main.yml

# specify the packages and the packager to use
- name: load OS specific variables (see ../vars/*)
  include_vars: "{{ ansible_os_family }}.yml"

- name: install required ppas on ubuntu machines
  apt_repository: repo="{{ item }}"
  with_items: apt_repos
  when: ansible_distribution == "Ubuntu" and apt_repos is defined

- name: install packages
  action: "{{ ansible_pkg_mgr }} pkg={{ item }} state=latest"
  with_items: packages

- name: install entr (a filesystem watcher)
  script: install_entr.sh
  when: ansible_os_family != 'Debian'

## created by default when installing package
# - name: create a wireshark group
#   group: name=wireshark state=present

- name: change dumpcap capabilities CAP_NET_RAW+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_RAW+eip'

- name: change dumpcap capabilities CAP_NET_ADMIN+eip => use wireshark as non-root
  capabilities: path="{{ dumpcap_path }}" capability='CAP_NET_ADMIN+eip'
